//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Serial
    {
        public int SerialID { get; set; }
        public string NumSerial { get; set; }
        public Nullable<System.DateTime> DateCrt { get; set; }
    }
}
